import type {ImportLead,ImportResult} from '../saas/contracts';
export interface CloudSession{accessToken:string;expiresAt:number;workspace:{id:string;name:string};refreshToken?:string}
const SESSION_KEY='saasCloudSession'; const PENDING_KEY='saasPendingImport';
export class ExtensionCloudClient{
 constructor(private apiBase:string){ }
 async session(){const value=await chrome.storage.local.get(SESSION_KEY);return value[SESSION_KEY] as CloudSession|undefined}
 async disconnect(){const session=await this.session();if(session)await fetch(`${this.apiBase}/api/v1/extension/disconnect`,{method:'POST',headers:{Authorization:`Bearer ${session.accessToken}`}}).catch(()=>undefined);await chrome.storage.local.remove(SESSION_KEY)}
 async import(extensionJobId:string,leads:ImportLead[],searchContext?:{keyword?:string;location?:string}){const session=await this.session();if(!session)throw new Error('CLOUD_AUTH_REQUIRED');const chunks=Array.from({length:Math.ceil(leads.length/250)},(_,i)=>leads.slice(i*250,(i+1)*250));const results:ImportResult[]=[];for(let batchNumber=0;batchNumber<chunks.length;batchNumber++){await chrome.storage.local.set({[PENDING_KEY]:{extensionJobId,batchNumber,total:chunks.length}});const response=await fetch(`${this.apiBase}/api/v1/leads/import`,{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${session.accessToken}`,'Idempotency-Key':`${extensionJobId}:${batchNumber}`},body:JSON.stringify({idempotencyKey:`${extensionJobId}:${batchNumber}`,extensionJobId,batchNumber,extensionVersion:chrome.runtime.getManifest().version,searchContext,leads:chunks[batchNumber]})});if(!response.ok)throw new Error(response.status>=500?'CLOUD_UNAVAILABLE':(await response.json() as {error:{code:string}}).error.code);results.push(await response.json() as ImportResult)}await chrome.storage.local.remove(PENDING_KEY);return results.reduce((a,r)=>({received:a.received+r.received,created:a.created+r.created,updated:a.updated+r.updated,duplicates:a.duplicates+r.duplicates,rejected:a.rejected+r.rejected,compatibility:r.compatibility}),{received:0,created:0,updated:0,duplicates:0,rejected:0,compatibility:'SUPPORTED'} as ImportResult)}
}
