import {ApiError} from './contracts';
export type CreditTransactionType='PURCHASE'|'PLAN_ALLOCATION'|'ENRICHMENT_USAGE'|'REFUND'|'ADMIN_ADJUSTMENT'|'EXPIRATION'|'PROMOTIONAL';
export interface CreditTransaction{id:string;organizationId:string;type:CreditTransactionType;amount:number;balanceAfter:number;referenceId?:string;description:string;createdAt:string}
interface Account{balance:number;reserved:number;transactions:CreditTransaction[];references:Set<string>}
export class CreditLedger{private accounts=new Map<string,Account>();private locks=new Map<string,Promise<void>>();private account(org:string){let a=this.accounts.get(org);if(!a){a={balance:0,reserved:0,transactions:[],references:new Set()};this.accounts.set(org,a)}return a}private async locked<T>(org:string,fn:()=>T|Promise<T>){const previous=this.locks.get(org)??Promise.resolve();let release!:()=>void;const gate=new Promise<void>(r=>release=r);this.locks.set(org,previous.then(()=>gate));await previous;try{return await fn()}finally{release()}}
async post(org:string,type:CreditTransactionType,amount:number,description:string,reference?:string){return this.locked(org,()=>{const a=this.account(org);if(reference&&a.references.has(reference))return a.transactions.find(t=>t.referenceId===reference)!;if(a.balance+amount<a.reserved)throw new ApiError('INSUFFICIENT_CREDITS','Insufficient available credits.',409,{available:a.balance-a.reserved,required:-amount});a.balance+=amount;const tx={id:crypto.randomUUID(),organizationId:org,type,amount,balanceAfter:a.balance,description,referenceId:reference,createdAt:new Date().toISOString()};a.transactions.push(tx);if(reference)a.references.add(reference);return tx})}
async reserve(org:string,amount:number){return this.locked(org,()=>{const a=this.account(org);if(a.balance-a.reserved<amount)throw new ApiError('INSUFFICIENT_CREDITS','Insufficient available credits.',409,{available:a.balance-a.reserved,required:amount});a.reserved+=amount;return a.reserved})}
async settle(org:string,reserved:number,consumed:number,jobId:string){return this.locked(org,()=>{const a=this.account(org);a.reserved=Math.max(0,a.reserved-reserved);if(consumed>a.balance)throw new ApiError('INSUFFICIENT_CREDITS','Credit settlement exceeds balance.',409);if(consumed){a.balance-=consumed;a.transactions.push({id:crypto.randomUUID(),organizationId:org,type:'ENRICHMENT_USAGE',amount:-consumed,balanceAfter:a.balance,description:'Successful enrichment operations',referenceId:jobId,createdAt:new Date().toISOString()})}return{balance:a.balance,reserved:a.reserved}})}
snapshot(org:string){const a=this.account(org);return{balance:a.balance,reserved:a.reserved,available:a.balance-a.reserved,transactions:[...a.transactions]}}}
