import {ApiError,type CloudLead,type ImportRequest,type ImportResult,type PlanCode,type Principal} from './contracts';
import {EntitlementsService} from './entitlements';
import {assertPermission} from './rbac';
const normalize=(v?:string)=>v?.trim().toLocaleLowerCase().replace(/^https?:\/\/(www\.)?/,'').replace(/[\s/()-]/g,'');
export type DuplicateMatch='EXACT_PLACE_ID'|'EXACT_MAPS_URL'|'STRONG_MATCH'|'POSSIBLE_MATCH'|'NEW';
export class LeadImportService{
 private leads:CloudLead[]=[];private completed=new Map<string,ImportResult>();private locks=new Map<string,Promise<void>>();
 constructor(private entitlements=new EntitlementsService()){}
 private async locked<T>(org:string,fn:()=>T|Promise<T>){const p=this.locks.get(org)??Promise.resolve();let release!:()=>void;const gate=new Promise<void>(r=>release=r);this.locks.set(org,p.then(()=>gate));await p;try{return await fn()}finally{release()}}
 private match(org:string,input:ImportRequest['leads'][number]):{lead?:CloudLead;match:DuplicateMatch}{const candidates=this.leads.filter(x=>x.organizationId===org);const exactPlace=input.placeId&&candidates.find(x=>x.placeId===input.placeId);if(exactPlace)return{lead:exactPlace,match:'EXACT_PLACE_ID'};const exactUrl=input.mapsUrl&&candidates.find(x=>normalize(x.mapsUrl)===normalize(input.mapsUrl));if(exactUrl)return{lead:exactUrl,match:'EXACT_MAPS_URL'};const strong=candidates.find(x=>(normalize(x.website)&&normalize(x.website)===normalize(input.website)&&normalize(x.phone)===normalize(input.phone))||(normalize(x.name)===normalize(input.name)&&normalize(x.address)===normalize(input.address)));return strong?{lead:strong,match:'STRONG_MATCH'}:{match:'NEW'}}
 async import(principal:Principal,plan:PlanCode,request:ImportRequest):Promise<ImportResult>{assertPermission(principal.role,'import:create');if(request.leads.length<1||request.leads.length>500)throw new ApiError('INVALID_IMPORT','Import batches must contain 1–500 leads.',422);const key=`${principal.organizationId}:${request.idempotencyKey}`;const existing=this.completed.get(key);if(existing)return existing;return this.locked(principal.organizationId,()=>{const raced=this.completed.get(key);if(raced)return raced;let created=0,updated=0,duplicates=0,rejected=0;const newInputs=request.leads.filter(x=>x.name?.trim()&&this.match(principal.organizationId,x).match==='NEW');const stored=this.leads.filter(x=>x.organizationId===principal.organizationId).length;if(!this.entitlements.canImportLeads(plan,stored,newInputs.length))throw new ApiError('LEAD_STORAGE_LIMIT_REACHED','Lead storage limit reached.',409,{current:stored,limit:this.entitlements.get(plan).maxCloudLeads});for(const input of request.leads){if(!input.name?.trim()){rejected++;continue}const found=this.match(principal.organizationId,input);if(found.lead){if(found.match==='STRONG_MATCH'||found.match.startsWith('EXACT_')){Object.assign(found.lead,Object.fromEntries(Object.entries(input).filter(([,v])=>v!==undefined&&v!=='')),{updatedAt:new Date().toISOString()});updated++}else duplicates++;continue}const now=new Date().toISOString();this.leads.push({...input,id:crypto.randomUUID(),organizationId:principal.organizationId,createdByUserId:principal.userId,source:'GOOGLE_MAPS',categories:input.categories??[],createdAt:now,updatedAt:now});created++}duplicates=request.leads.length-created-updated-rejected;const result={received:request.leads.length,created,updated,duplicates,rejected,compatibility:'SUPPORTED' as const};this.completed.set(key,result);return result})}
 list(principal:Principal){assertPermission(principal.role,'lead:view');return this.leads.filter(x=>x.organizationId===principal.organizationId)}
}
