-- Phase 3 bootstrap; production uses `prisma migrate deploy`.
CREATE TYPE "UserStatus" AS ENUM ('ACTIVE','SUSPENDED','DELETED'); CREATE TYPE "OrganizationStatus" AS ENUM ('ACTIVE','SUSPENDED','CANCELLED'); CREATE TYPE "OrganizationRole" AS ENUM ('OWNER','ADMIN','MEMBER','VIEWER');
CREATE TABLE "User" ("id" UUID PRIMARY KEY,"email" TEXT NOT NULL UNIQUE,"passwordHash" TEXT,"name" TEXT,"emailVerifiedAt" TIMESTAMPTZ,"status" "UserStatus" NOT NULL DEFAULT 'ACTIVE',"platformAdmin" BOOLEAN NOT NULL DEFAULT false,"createdAt" TIMESTAMPTZ NOT NULL DEFAULT now(),"updatedAt" TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE "Organization" ("id" UUID PRIMARY KEY,"name" TEXT NOT NULL,"slug" TEXT NOT NULL UNIQUE,"ownerUserId" UUID NOT NULL REFERENCES "User"("id"),"status" "OrganizationStatus" NOT NULL DEFAULT 'ACTIVE',"deletionRequestedAt" TIMESTAMPTZ,"createdAt" TIMESTAMPTZ NOT NULL DEFAULT now(),"updatedAt" TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE "OrganizationMember" ("id" UUID PRIMARY KEY,"organizationId" UUID NOT NULL REFERENCES "Organization"("id"),"userId" UUID NOT NULL REFERENCES "User"("id"),"role" "OrganizationRole" NOT NULL,"joinedAt" TIMESTAMPTZ NOT NULL DEFAULT now(),UNIQUE("organizationId","userId"));
CREATE TABLE "Lead" ("id" UUID PRIMARY KEY,"organizationId" UUID NOT NULL REFERENCES "Organization"("id"),"name" TEXT NOT NULL,"placeId" TEXT,"mapsUrl" TEXT,"website" TEXT,"phone" TEXT,"address" TEXT,"city" TEXT,"source" TEXT NOT NULL,"createdByUserId" UUID NOT NULL,"deletedAt" TIMESTAMPTZ,"createdAt" TIMESTAMPTZ NOT NULL DEFAULT now(),"updatedAt" TIMESTAMPTZ NOT NULL DEFAULT now(),UNIQUE("organizationId","placeId")); CREATE INDEX "Lead_org_created_idx" ON "Lead"("organizationId","createdAt"); CREATE INDEX "Lead_org_name_idx" ON "Lead"("organizationId","name");
CREATE TABLE "LeadList" ("id" UUID PRIMARY KEY,"organizationId" UUID NOT NULL REFERENCES "Organization"("id"),"name" TEXT NOT NULL,"createdByUserId" UUID NOT NULL,"deletedAt" TIMESTAMPTZ,"createdAt" TIMESTAMPTZ NOT NULL DEFAULT now(),"updatedAt" TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE "LeadListMember" ("listId" UUID NOT NULL REFERENCES "LeadList"("id"),"leadId" UUID NOT NULL REFERENCES "Lead"("id"),"addedByUserId" UUID NOT NULL,"addedAt" TIMESTAMPTZ NOT NULL DEFAULT now(),PRIMARY KEY("listId","leadId"));
CREATE TABLE "ScrapeImport" ("id" UUID PRIMARY KEY,"organizationId" UUID NOT NULL REFERENCES "Organization"("id"),"createdByUserId" UUID NOT NULL,"extensionJobId" TEXT NOT NULL,"idempotencyKey" TEXT NOT NULL,"batchNumber" INTEGER NOT NULL,"extensionVersion" TEXT NOT NULL,"receivedCount" INTEGER NOT NULL,"createdCount" INTEGER NOT NULL,"updatedCount" INTEGER NOT NULL,"duplicateCount" INTEGER NOT NULL,"rejectedCount" INTEGER NOT NULL,"importedAt" TIMESTAMPTZ NOT NULL DEFAULT now(),UNIQUE("organizationId","idempotencyKey"),UNIQUE("organizationId","extensionJobId","batchNumber"));
CREATE TABLE "CreditTransaction" ("id" UUID PRIMARY KEY,"organizationId" UUID NOT NULL REFERENCES "Organization"("id"),"type" TEXT NOT NULL,"amount" INTEGER NOT NULL,"balanceAfter" INTEGER NOT NULL CHECK ("balanceAfter">=0),"referenceType" TEXT,"referenceId" TEXT,"description" TEXT NOT NULL,"createdAt" TIMESTAMPTZ NOT NULL DEFAULT now(),UNIQUE("organizationId","referenceType","referenceId","type"));
CREATE TABLE "WebhookEvent" ("id" UUID PRIMARY KEY,"provider" TEXT NOT NULL,"externalEventId" TEXT NOT NULL,"eventType" TEXT NOT NULL,"payloadHash" TEXT NOT NULL,"processedAt" TIMESTAMPTZ NOT NULL DEFAULT now(),UNIQUE("provider","externalEventId"));
CREATE TABLE "AuditLog" ("id" UUID PRIMARY KEY,"organizationId" UUID REFERENCES "Organization"("id"),"userId" UUID,"action" TEXT NOT NULL,"resourceType" TEXT,"resourceId" TEXT,"metadata" JSONB,"requestId" TEXT NOT NULL,"createdAt" TIMESTAMPTZ NOT NULL DEFAULT now()); CREATE INDEX "Audit_org_created_idx" ON "AuditLog"("organizationId","createdAt");
